import type { Entry, Product, RawMaterialStock, SocialStatEntry, Supplier } from "./types";

function daysAgo(n: number): string {
  const d = new Date("2026-07-10T09:00:00.000Z");
  d.setUTCDate(d.getUTCDate() - n);
  return d.toISOString();
}

export const initialProducts: Product[] = [
  {
    id: "prod-classic",
    name: "Classic Cocoa Spread",
    standardPrice: 180,
    pricingMode: "manual",
    marginPercent: 30,
    friendPrice: 150,
    wholesalePrice: 130,
    stockQty: 42,
    lowStockThreshold: 15,
    batchYield: 40,
    recipeIngredients: [
      { id: "ri-classic-cocoa", materialId: "rm-cocoa", quantity: 2 },
      { id: "ri-classic-sugar", materialId: "rm-sugar", quantity: 1.5 },
      { id: "ri-classic-oil", materialId: "rm-oil", quantity: 1 },
      { id: "ri-classic-jars", materialId: "rm-jars", quantity: 40 },
      { id: "ri-classic-labels", materialId: "rm-labels", quantity: 40 },
    ],
    recipeLabor: [{ id: "rl-classic", label: "Labor", cost: 320 }],
    recipeMisc: [{ id: "rmc-classic", label: "Electricity, gas", cost: 160 }],
  },
  {
    id: "prod-dark",
    name: "Dark Cocoa Spread",
    standardPrice: 200,
    pricingMode: "manual",
    marginPercent: 30,
    friendPrice: 170,
    wholesalePrice: 150,
    stockQty: 25,
    lowStockThreshold: 15,
    batchYield: 35,
    recipeIngredients: [
      { id: "ri-dark-cocoa", materialId: "rm-cocoa", quantity: 2.5 },
      { id: "ri-dark-sugar", materialId: "rm-sugar", quantity: 1 },
      { id: "ri-dark-oil", materialId: "rm-oil", quantity: 1 },
      { id: "ri-dark-jars", materialId: "rm-jars", quantity: 35 },
      { id: "ri-dark-labels", materialId: "rm-labels", quantity: 35 },
    ],
    recipeLabor: [{ id: "rl-dark", label: "Labor", cost: 280 }],
    recipeMisc: [{ id: "rmc-dark", label: "Electricity, gas", cost: 175 }],
  },
  {
    id: "prod-crunch",
    name: "Cocoa Crunch",
    standardPrice: 190,
    pricingMode: "manual",
    marginPercent: 30,
    friendPrice: 160,
    wholesalePrice: 140,
    stockQty: 12,
    lowStockThreshold: 15,
    batchYield: 40,
    recipeIngredients: [
      { id: "ri-crunch-cocoa", materialId: "rm-cocoa", quantity: 2 },
      { id: "ri-crunch-sugar", materialId: "rm-sugar", quantity: 1.5 },
      { id: "ri-crunch-oil", materialId: "rm-oil", quantity: 1 },
      { id: "ri-crunch-mixins", materialId: "rm-crunch-mixins", quantity: 1 },
      { id: "ri-crunch-jars", materialId: "rm-jars", quantity: 40 },
      { id: "ri-crunch-labels", materialId: "rm-labels", quantity: 40 },
    ],
    recipeLabor: [{ id: "rl-crunch", label: "Labor", cost: 320 }],
    recipeMisc: [{ id: "rmc-crunch", label: "Electricity, gas", cost: 160 }],
  },
];

export const initialRawMaterials: RawMaterialStock[] = [
  { id: "rm-cocoa", name: "Cocoa beans", unit: "kg", qty: 18, lowStockThreshold: 10, perBatchQty: 2, color: null, unitCost: 225 },
  { id: "rm-jars", name: "Jars", unit: "pcs", qty: 65, lowStockThreshold: 30, perBatchQty: 40, color: null, unitCost: 12 },
  { id: "rm-labels", name: "Labels", unit: "pcs", qty: 90, lowStockThreshold: 30, perBatchQty: 40, color: null, unitCost: 3 },
  { id: "rm-oil", name: "Oil", unit: "L", qty: 6, lowStockThreshold: 4, perBatchQty: 1, color: null, unitCost: 120 },
  { id: "rm-sugar", name: "Sugar", unit: "kg", qty: 9, lowStockThreshold: 5, perBatchQty: 1.5, color: null, unitCost: 100 },
  {
    id: "rm-crunch-mixins",
    name: "Crunch mix-ins",
    unit: "kg",
    qty: 5,
    lowStockThreshold: 2,
    perBatchQty: 1,
    color: null,
    unitCost: 200,
  },
];

export const initialSuppliers: Supplier[] = [
  {
    id: "sup-palengke",
    name: "Aling Nena's Market Stall",
    type: "raw_materials",
    items: "Cocoa beans, sugar",
    lastPrice: 90,
    priceHistory: [
      { date: daysAgo(60), price: 82 },
      { date: daysAgo(30), price: 85 },
      { date: daysAgo(5), price: 90 },
    ],
    contact: "0917-555-0142",
  },
  {
    id: "sup-jars",
    name: "Manila Glass & Jar Co.",
    type: "packaging",
    items: "Glass jars, lids",
    lastPrice: 12,
    priceHistory: [
      { date: daysAgo(60), price: 11 },
      { date: daysAgo(20), price: 12 },
    ],
    contact: "0918-555-0033",
  },
  {
    id: "sup-labels",
    name: "Quick Print Labels",
    type: "packaging",
    items: "Printed labels",
    lastPrice: 3,
    priceHistory: [{ date: daysAgo(45), price: 3 }],
    contact: "0919-555-0087",
  },
];

export const initialSocialStats: SocialStatEntry[] = [
  { id: "soc-1", platform: "Facebook", weekOf: daysAgo(21), followers: 1200, reach: 4300, engagements: 310 },
  { id: "soc-2", platform: "Facebook", weekOf: daysAgo(14), followers: 1250, reach: 5100, engagements: 380 },
  { id: "soc-3", platform: "Facebook", weekOf: daysAgo(7), followers: 1310, reach: 6800, engagements: 510 },
  { id: "soc-4", platform: "TikTok", weekOf: daysAgo(21), followers: 800, reach: 9000, engagements: 620 },
  { id: "soc-5", platform: "TikTok", weekOf: daysAgo(14), followers: 950, reach: 15200, engagements: 1240 },
  { id: "soc-6", platform: "TikTok", weekOf: daysAgo(7), followers: 1100, reach: 21000, engagements: 1890 },
  { id: "soc-7", platform: "Instagram", weekOf: daysAgo(21), followers: 600, reach: 2100, engagements: 140 },
  { id: "soc-8", platform: "Instagram", weekOf: daysAgo(14), followers: 640, reach: 2600, engagements: 190 },
  { id: "soc-9", platform: "Instagram", weekOf: daysAgo(7), followers: 690, reach: 3400, engagements: 260 },
];

export const initialEntries: Entry[] = [
  {
    id: "seed-1",
    timestamp: daysAgo(20),
    type: "SALE",
    amount: 2160,
    quantity: 12,
    unit: "jars",
    sku: "Classic Cocoa Spread",
    counterparty: "Aling Nena",
    location: "Quezon City",
    priceType: "wholesale",
    category: null,
    rawText: "Sold 12 jars to Aling Nena, wholesale, 2160",
    confidence: 0.95,
  },
  {
    id: "seed-2",
    timestamp: daysAgo(18),
    type: "EXPENSE",
    amount: 450,
    quantity: 5,
    unit: "kg",
    sku: "Cocoa beans",
    counterparty: "the market",
    location: null,
    priceType: null,
    category: "raw_materials",
    rawText: "Bought 5kg cocoa beans at the market, 450",
    confidence: 0.93,
  },
  {
    id: "seed-3",
    timestamp: daysAgo(15),
    type: "SALE",
    amount: 3600,
    quantity: 20,
    unit: "jars",
    sku: "Classic Cocoa Spread",
    counterparty: "Walk-in customers",
    location: "Marikina",
    priceType: "standard",
    category: null,
    rawText: "Sold 20 jars retail, 3600 total",
    confidence: 0.9,
  },
  {
    id: "seed-4",
    timestamp: daysAgo(12),
    type: "EXPENSE",
    amount: 2300,
    quantity: null,
    unit: null,
    sku: null,
    counterparty: null,
    location: null,
    priceType: null,
    category: "utilities",
    rawText: "Electricity this month, 2300",
    confidence: 0.97,
  },
  {
    id: "seed-5",
    timestamp: daysAgo(10),
    type: "SALE",
    amount: 450,
    quantity: 3,
    unit: "jars",
    sku: "Dark Cocoa Spread",
    counterparty: "Marco",
    location: null,
    priceType: "friend",
    category: null,
    rawText: "Gave 3 jars friend rate to Marco, 150 each",
    confidence: 0.88,
  },
  {
    id: "seed-6",
    timestamp: daysAgo(8),
    type: "WASTE",
    amount: 260,
    quantity: 2,
    unit: "jars",
    sku: "Classic Cocoa Spread",
    counterparty: null,
    location: null,
    priceType: null,
    category: null,
    rawText: "2 jars spoiled, had to throw them out",
    confidence: 0.85,
  },
  {
    id: "seed-7",
    timestamp: daysAgo(6),
    type: "SALE",
    amount: 2800,
    quantity: 20,
    unit: "jars",
    sku: "Cocoa Crunch",
    counterparty: "Sari-sari store - Tita Baby",
    location: "Marikina",
    priceType: "wholesale",
    category: null,
    rawText: "Sold 20 jars of cocoa crunch to Tita Baby, wholesale, 2800",
    confidence: 0.9,
  },
  {
    id: "seed-8",
    timestamp: daysAgo(4),
    type: "EXPENSE",
    amount: 780,
    quantity: 65,
    unit: "pcs",
    sku: "Jars",
    counterparty: "Manila Glass & Jar Co.",
    location: null,
    priceType: null,
    category: "packaging",
    rawText: "Bought 65 new jars, 780 pesos",
    confidence: 0.86,
  },
  {
    id: "seed-9",
    timestamp: daysAgo(2),
    type: "SALE",
    amount: 900,
    quantity: 5,
    unit: "jars",
    sku: "Classic Cocoa Spread",
    counterparty: "Ana",
    location: "Quezon City",
    priceType: "standard",
    category: null,
    rawText: "Sold 5 jars to Ana, 180 each",
    confidence: 0.92,
  },
  {
    id: "seed-10",
    timestamp: daysAgo(1),
    type: "EXPENSE",
    amount: 600,
    quantity: null,
    unit: null,
    sku: null,
    counterparty: "tricycle",
    location: null,
    priceType: null,
    category: "transport",
    rawText: "Delivery fares this week, 600",
    confidence: 0.8,
  },
];
